export const defaultExercises = [
  { value: "bench", label: "Bænk" },
  { value: "upper-dumbell", label: "Upper dumbell" },
  { value: "dips", label: "Dips" },
  { value: "skulderpress", label: "Skulderpress" },
  { value: "side-laterals", label: "Side Laterals" },
  { value: "tricep-extensions", label: "Tricep extensions" },
  { value: "pullups", label: "Pullups" },
  { value: "dumbell-rows", label: "Dumbell Rows" },
  { value: "pulldown-wide", label: "Pulldown wide" },
  { value: "upright-row", label: "Upright row" },
  { value: "ryg", label: "Ryg" },
  { value: "bicep-curl", label: "Bicep curl" },
  { value: "doedloeft", label: "Dødløft" },
  { value: "squat", label: "Squat" },
  { value: "calf-raises", label: "Calf raises" },
  { value: "mave-hjul", label: "Mave hjul" },
  { value: "pulldown-short", label: "Pulldown short" },
  { value: "rows", label: "Rows" },
  { value: "rows-dumbell", label: "Rows dumbell" },
];
